language: go
go:
  -"1.11"
os: osx

service: 
  - docker
  
env: GO111MODULE=on

before_install:
  - docker pull golang
  - docker run golang
  - GO111MODULE=on && go mod download
  - GO111MODULE=on && go mod vendor

install: true

script: go test -v ./...

